name: Build

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release

    - shell: bash
      run: |
        mv target/release/resistor resistor
        chmod 777 resistor
        tar cpfz resistor_linux_x86_64.tar.gz resistor

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: resistor_linux_x86_64.tar.gz

  windows_build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release

    - name: Prepare artifact
      shell: pwsh
      run: |
        Move-Item target/release/resistor.exe resistor.exe
        Compress-Archive -Path resistor.exe -DestinationPath resistor_windows_x86_64.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: resistor_windows_x86_64.zip

  macos_build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release

    - shell: bash
      run: |
        mv target/release/resistor resistor
        chmod 777 resistor
        tar cpfz resistor_macos_x86_64.tar.gz resistor

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: resistor_macos_x86_64.tar.gz
